<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERPSystem.Domain\ERPSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Catalog\Commands\" />
    <Folder Include="Features\Catalog\Queries\" />
  </ItemGroup>

</Project>
